### ISSUE TITLE
 ModuleNotFoundError: No module named 'pygenn'

### ISSUE THREAD

**Issue by Vivek1258** [genn-team/tensor_genn#7]
OS : Ubuntu 18.04.3 LTS
When I try to run conversion_example.py It is giving the following error 
Please help me check what the problem is? 
 
(vivekenv) vivek@vivek-HP-Laptop-15q-ds0xxx:~/tensor_genn$ python3 conversion_example.py

/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/vivek/anaconda3/envs/vivekenv/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "conversion_example.py", line 4, in <module>
    import tensor_genn as tg
  File "/home/vivek/tensor_genn/tensor_genn/__init__.py", line 1, in <module>
    from .base import convert_model
  File "/home/vivek/tensor_genn/tensor_genn/base.py", line 4, in <module>
    from pygenn import genn_model, genn_wrapper
ModuleNotFoundError: No module named 'pygenn'

A similar error is seen when I try to run it on the jupyter notebook :
No module named 'tensor_genn.algorithms'

Thank you

**Comment by ajaysub110** [comment]
Hi Vivek,

Seems as though you haven't installed PyGeNN which is one of the dependencies for this library. In order to do so, pick the .whl file corresponding to your platform from [here](https://github.com/genn-team/genn/pull/234) and run `pip install <filename>` to install GeNN 4.0.0 and PyGeNN. 
Once this is done, you should be able to run the `conversion_example.py` file assuming you have TensorFlow, Numpy and Matplotlib installed already.

I'll add a requirements file with the dependencies so that this won't be an issue in the future.

Ajay

**Comment by Vivek1258** [comment]
ok 
Thanks
